steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - streaming
      - --trigger-http
      - --set-env-vars BQ_DATASET=_BQ_DATASET,BQ_TABLE=_BQ_TABLE
      - --source=streaming.py
      - --runtime=python38

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - report
      - --trigger-http
      - --set-env-vars SLACK_REPORT_CHANNEL=_SLACK_REPORT_CHANNEL,BQ_DATASET=_BQ_DATASET,BQ_TABLE=_BQ_TABLE
      - --source=timeliner.py
      - --runtime=python38
