steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - streaming
      - --region=asia-northeast1
      - --trigger-http
      - --set-env-vars=BQ_DATASET=$_BQ_DATASET,BQ_TABLE=$_BQ_TABLE
      - --source=streaming
      - --runtime=python37

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - report
      - --region=asia-northeast1
      - --trigger-http
      - --set-env-vars=SLACK_REPORT_CHANNEL=$_SLACK_REPORT_CHANNEL,BQ_DATASET=$_BQ_DATASET,BQ_TABLE=$_BQ_TABLE
      - --source=report
      - --runtime=python37
